name: school_bus_service
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  lottie: ^3.1.2
  equatable: ^2.0.5
  collection: ^1.18.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  flutter_localizations:
    sdk: flutter
  skeleton_text: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Bold.ttf

    - family: Dancing Script
      fonts:
        - asset: fonts/DancingScript-Regular.ttf
        - asset: fonts/DancingScript-Medium.ttf
        - asset: fonts/DancingScript-Bold.ttf