// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7_Z3Zkwa-TPL4q2pYzfJwyTgMu38lbt4',
    appId: '1:1034518356915:web:86edbc6443eef81caea1c6',
    messagingSenderId: '1034518356915',
    projectId: 'school-bus-service-3e18d',
    authDomain: 'school-bus-service-3e18d.firebaseapp.com',
    storageBucket: 'school-bus-service-3e18d.appspot.com',
    measurementId: 'G-EY5FSZHZK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlP6xbBmbC_1qtiptB4eB8N48Z8cCCZsw',
    appId: '1:1034518356915:android:5865dce7d7cf3590aea1c6',
    messagingSenderId: '1034518356915',
    projectId: 'school-bus-service-3e18d',
    storageBucket: 'school-bus-service-3e18d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA85F1ggqKj1Coeav9BgJFMcZywNlYLFI',
    appId: '1:1034518356915:ios:eeebdbb52a4e5fbfaea1c6',
    messagingSenderId: '1034518356915',
    projectId: 'school-bus-service-3e18d',
    storageBucket: 'school-bus-service-3e18d.appspot.com',
    iosBundleId: 'com.example.schoolBusService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA85F1ggqKj1Coeav9BgJFMcZywNlYLFI',
    appId: '1:1034518356915:ios:eeebdbb52a4e5fbfaea1c6',
    messagingSenderId: '1034518356915',
    projectId: 'school-bus-service-3e18d',
    storageBucket: 'school-bus-service-3e18d.appspot.com',
    iosBundleId: 'com.example.schoolBusService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7_Z3Zkwa-TPL4q2pYzfJwyTgMu38lbt4',
    appId: '1:1034518356915:web:99552462aadcedefaea1c6',
    messagingSenderId: '1034518356915',
    projectId: 'school-bus-service-3e18d',
    authDomain: 'school-bus-service-3e18d.firebaseapp.com',
    storageBucket: 'school-bus-service-3e18d.appspot.com',
    measurementId: 'G-X4SGLLWWGN',
  );
}
